In [1]:
import cv2


In [2]:
photo=cv2.imread('00-Divo_BUGATTI.jpg')

In [3]:
cv2.imshow('hi',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import  numpy


In [5]:
arr=numpy.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12],[13,14,15,16]])


In [6]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
arr.shape


(4, 4)

In [8]:
photo


array([[[214, 210, 205],
        [214, 210, 205],
        [214, 210, 205],
        ...,
        [189, 168, 141],
        [189, 168, 141],
        [189, 168, 141]],

       [[214, 210, 205],
        [214, 210, 205],
        [214, 210, 205],
        ...,
        [189, 168, 141],
        [189, 168, 141],
        [189, 168, 141]],

       [[214, 210, 205],
        [214, 210, 205],
        [214, 210, 205],
        ...,
        [189, 168, 141],
        [189, 168, 141],
        [189, 168, 141]],

       ...,

       [[131, 121, 114],
        [117, 107, 100],
        [118, 108, 101],
        ...,
        [ 98,  88,  81],
        [102,  92,  85],
        [105,  95,  88]],

       [[136, 126, 119],
        [132, 122, 115],
        [127, 117, 110],
        ...,
        [ 94,  84,  77],
        [101,  91,  84],
        [104,  94,  87]],

       [[134, 124, 117],
        [153, 143, 136],
        [155, 145, 138],
        ...,
        [ 92,  82,  75],
        [100,  90,  83],
        [101,  91,  84]]

In [9]:
photo.shape


(800, 1540, 3)

In [10]:
photo[0][0]

array([214, 210, 205], dtype=uint8)

In [11]:
photo[0][0]=[0,255,0]

In [12]:
photo[0][0]

array([  0, 255,   0], dtype=uint8)

In [13]:
cv2.imshow('hi',photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [15]:
cpphoto=photo[500:800,400:1000]

In [16]:
cpphoto


array([[[  8,   2,   0],
        [ 14,   9,   0],
        [ 19,  14,   5],
        ...,
        [ 24,  26,  44],
        [ 30,  33,  54],
        [ 34,  39,  64]],

       [[ 98,  91,  82],
        [152, 143, 133],
        [200, 191, 182],
        ...,
        [ 22,  25,  40],
        [ 24,  28,  47],
        [ 25,  31,  54]],

       [[198, 188, 178],
        [227, 215, 203],
        [241, 229, 219],
        ...,
        [ 26,  27,  41],
        [ 25,  27,  45],
        [ 22,  27,  48]],

       ...,

       [[ 96,  87,  83],
        [101,  92,  88],
        [106,  97,  93],
        ...,
        [  5,   5,   5],
        [  5,   5,   5],
        [  5,   5,   5]],

       [[106,  97,  93],
        [108,  99,  95],
        [110, 101,  97],
        ...,
        [  7,   7,   7],
        [  7,   7,   7],
        [  7,   7,   7]],

       [[113, 104, 100],
        [109, 100,  96],
        [106,  97,  93],
        ...,
        [  7,   7,   7],
        [  7,   7,   7],
        [  7,   7,   7]]

In [17]:
cv2.imshow('hi',cpphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
cn=numpy.zeros((200,300))

In [19]:
cn


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
cv2.imshow('hi',cn)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
cv2.COLOR_BGR2GRAY

6

In [22]:
gphoto=cv2.cvtColor(photo,cv2.COLOR_BGR2GRAY )

In [23]:
gphoto

array([[150, 209, 209, ..., 162, 162, 162],
       [209, 209, 209, ..., 162, 162, 162],
       [209, 209, 209, ..., 162, 162, 162],
       ...,
       [120, 106, 107, ...,  87,  91,  94],
       [125, 121, 116, ...,  83,  90,  93],
       [123, 142, 144, ...,  81,  89,  90]], dtype=uint8)

In [24]:
cv2.imshow('hi',gphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [25]:
gphoto.shape

(800, 1540)